spring:
  main:
    web-application-type: NONE
  liquibase:
    enabled: true
    default-schema: public
    liquibase-schema: public
  jpa.hibernate.ddl-auto: validate
logging:
  level:
    org.hibernate.SQL: DEBUG
