logging:
  level:
      org.hibernate:
        SQL: DEBUG
        stat: ERROR
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false # way too noisy to be worth it
